title: Rom Hack Studios
description: Download the latest Emerald Crest patch here.
theme: just-the-docs

url: https://romhackstudios.github.io/

aux_links:
  Discord: https://discord.gg/aaghat-s-server-965900074532081674

color_scheme: midnight

plugins:
  - jekyll-seo-tag
  
favicon_ico: "/ico_shuffle_2599.png"

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

    ga_tracking: G-39V22GPEHQ
    ga_tracking_anonymize_ip: true
